version: "3"
services:
  proxy:
    container_name: proxy
    image: 'nginx_proxy'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./proxy/data:/data
      - ./proxy/data/letsencrypt:/etc/letsencrypt
  web:
    container_name: web
    image: express_server
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app
    command: bash -c "npm install && npm run dev"