version: '3'
services:
  servermysql:
    image: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - "./data:/var/lib/mysql"