version: '3'
services:
  serverpostgres:
    image: postgres_server
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata 
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
